### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by gedw99** [cirello-io/runner#1]
Love how this is designed. Eland supervisor trees !

I am having some trouble understanding how to run many processes.
My understanding is that i use formations to do this.
But i cant seem to make it find the Procfile. ??

makefFile:
```
runner -formation $(PWD)/nats/Procfile

runner: open Procfile: no such file or directory

````

Procfile-nats:
````
workdir: $PWD
observe: *.go *.js
ignore: /vendor
build-server: make nats-start
web: restart=fail waitfor=localhost:8888 ./server serve
web-a: group=web restart=always waitfor=localhost:8888 ./server serve alpha
web-b: group=web restart=always waitfor=localhost:8888 ./server serve bravo
db: restart=failure waitfor=web ./server db

````

**Comment by gedw99** [comment]
I worked it out. Just had to read more.

Wondering if the build-*** is respected by the formation-*** ?
For example if i want to run 2 NATS

```
workdir: $PWD
observe: *.go *.js
ignore: /vendor
formation: nats=1 redis=1 cen=1

# start up precompiled stuff
build-nats: make cene-nats-start
build-redis: make cene-redis-start
build-cen: make cen-run
```

**Comment by ucirello** [comment]
The formation parameter should only affect changes to non build targets.
