### ISSUE TITLE
windows arm64

### ISSUE THREAD

**Issue by gedw99** [cirello-io/runner#25]
there is no reason this can't work on windows, both amd64 and arm64

it works fine on darwin and linux, both amd64 and arm64.

The issue is the call to the shell. I think the waiter call it. Maybe we just need to work out the equivalent for window ?

See here:
https://github.com/mattn/goreman/blob/master/proc_windows.go

```
exec: "sh": executable file not found in %PATH%
```

Procfile:

```sh

workdir: .
nats: nats-server_windows_arm64.exe -js

```

Terminal:

```sh
Microsoft Windows [Version 10.0.22631.3374]
(c) Microsoft Corporation. All rights reserved.

C:\Users\admin>cd Desktop
C:\Users\admin\Desktop>runner_windows_arm64.exe
nats.0 : running "nats-server_windows_arm64.exe -js"
nats.0 : listening on 5000
nats.0 :
nats.0 : exec error nats.0: (nats-server_windows_arm64.exe -js) exec: "sh": executable file not found in %PATH%
nats.0 : finished "nats-server_windows_arm64.exe -js"
runner: starting service discovery on 127.0.0.1:64000
2024/03/28 20:27:13 starting tree-6931220813577946861
2024/03/28 20:27:13 detected change in child processes list
2024/03/28 20:27:13 tree-6931220813577946861 child started

**Comment by ucirello** [comment]
Last time I tried to make it work in Windows, lots of other smaller things broke, like the `waitfor` facet. But at the same time, I don't think anyone, but me, uses any other facet than the `runner` one.

Please, try c21c08ed9d14ac594f8ef14d818353748d745968

**Comment by ucirello** [comment]
I just managed to validate on a Windows machine here and now it works.

**Comment by gedw99** [comment]
wow that was quick. thanks you so much,

I just tested it on windows arm64 and it worked for me too.
