### ISSUE TITLE
http://localhost:64000 output is delayed

### ISSUE THREAD

**Issue by gedw99** [cirello-io/runner#34]
I dont know if this is by design, but on MAC ARM64, I often dont see any output in the web gui until I kill the runner process.

https://github.com/ryoid/go-streaming-html-ooo might be a better way to stream updates to the GUI. It's just a simple way that uses no javascript and works in all browsers these days. It holds a connection to the server and the server just flushes the response to update any Components.

We would then represent each line in the ProcFile with a Component with the slots.

You can see what I mean by by just doing a go run . on the code in https://github.com/ryoid/go-streaming-html-ooo.

I am only bringing this up because the Out of Order streaming approach might help and be a very nice and simple way to update the GUI, when anything on the server changes.

in https://github.com/cirello-io/runner/blob/master/runner/web.go, it would mean that no web sockets are needed of the terminal to html is needed.  We just need to render the Web Components with golang, and flush updates as they come in.

I am really loving using runner BTW. Its very useful

**Comment by ucirello** [comment]
@gedw99 thanks for this report. I use this feature everyday and it works correctly for me on a Mac ARM64 and Google Chrome. Please double check your setup. Thank you.

**Comment by gedw99** [comment]
ok thanks.

I will try again ..
