### ISSUE TITLE
just noticed that latest tag does not run on windows 

### ISSUE THREAD

**Issue by gedw99** [cirello-io/runner#52]
used to work : https://github.com/cirello-io/runner/issues/25

Can send a PR if needed.

Will get an output, but away from laptop and it failed in ci.

amd64 is where I saw it fails.

will test on arm64

**Comment by ucirello** [comment]
Indeed `runner/v2` does not support Windows yet.

I may restore this support in a later release - the major version bump was exactly to indicate that `runner/v2` is not compatible with `runner`.

I'll leave this issue open until I make a final decision.

**Comment by ucirello** [comment]
@gedw99 -- try this commit please: https://github.com/cirello-io/runner/commit/2f8ad4584f3660f00d8aaedf4c1203e6947fd746
